/**
 * 化學 2048 — 完整週期表元素資料 (118 elements)
 *
 * 每個元素的欄位:
 *   no, symbol, en, zh                — 識別資訊
 *   period, group, category           — 週期表位置
 *   atomic_weight                     — 原子量
 *   electron_config                   — 電子組態
 *   electronegativity                 — 電負度 (Pauling, null = N/A)
 *   melting_pt, boiling_pt            — 熔點/沸點 (K)
 *   state_at_stp                      — 標準狀態
 *   discovery_year, discoverer        — 發現
 *   uses_zh, uses_en                  — 用途 (中英對照)
 *   fun_fact_zh                       — 冷知識
 *   bg, color                         — 棋盤上色
 *
 * 前 20 個元素 (H~Ca) 保留原配色；21~118 按 category 上色 (標準週期表配色)。
 */

(function () {
    'use strict';

    // ── Category-based color palette for elements 21+ ─────────────
    const CAT_COLORS = {
        nonmetal:           { bg: "#eee4da", color: "#776e65" },
        noble_gas:          { bg: "#a66dd4", color: "#f9f6f2" },
        alkali_metal:       { bg: "#ff6b6b", color: "#f9f6f2" },
        alkaline_earth:     { bg: "#ffa502", color: "#f9f6f2" },
        metalloid:          { bg: "#4d96ff", color: "#f9f6f2" },
        post_transition:    { bg: "#6bcb77", color: "#f9f6f2" },
        transition_metal:   { bg: "#ffd93d", color: "#776e65" },
        lanthanide:         { bg: "#ec407a", color: "#f9f6f2" },
        actinide:           { bg: "#c2185b", color: "#f9f6f2" },
        halogen:            { bg: "#4dd0e1", color: "#776e65" },
        unknown:            { bg: "#bdbdbd", color: "#f9f6f2" },
    };

    // Helper: build entry, allow per-element bg/color override
    function E(no, symbol, en, zh, period, group, category, ext) {
        const base = {
            no: no, symbol: symbol, en: en, zh: zh,
            period: period, group: group, category: category,
            atomic_weight: null, electron_config: "", electronegativity: null,
            melting_pt: null, boiling_pt: null, state_at_stp: "unknown",
            discovery_year: null, discoverer: "",
            uses_zh: "", uses_en: "", fun_fact_zh: "",
        };
        Object.assign(base, ext || {});
        if (!base.bg) {
            const c = CAT_COLORS[category] || CAT_COLORS.unknown;
            base.bg = c.bg; base.color = c.color;
        }
        return base;
    }

    // ── Elements 1-20: original game colors preserved ────────────
    const elements = [
        E(1, "H", "Hydrogen", "氫", 1, 1, "nonmetal", {
            atomic_weight: 1.008, electron_config: "1s¹", electronegativity: 2.20,
            melting_pt: 13.99, boiling_pt: 20.27, state_at_stp: "gas",
            discovery_year: 1766, discoverer: "Henry Cavendish",
            uses_zh: "氫是宇宙中最豐富的元素，用於製造氨、合成石油、火箭燃料以及氫燃料電池。",
            uses_en: "Most abundant element in the universe; used in ammonia production, oil refining, rocket fuel, and hydrogen fuel cells.",
            fun_fact_zh: "太陽 75% 的質量都是氫；氫氣比空氣輕 14 倍。",
            bg: "#eee4da", color: "#776e65",
        }),
        E(2, "He", "Helium", "氦", 1, 18, "noble_gas", {
            atomic_weight: 4.003, electron_config: "1s²", electronegativity: null,
            melting_pt: 0.95, boiling_pt: 4.22, state_at_stp: "gas",
            discovery_year: 1868, discoverer: "Pierre Janssen",
            uses_zh: "氦氣用於充填氣球、飛艇和潛水呼吸氣，液態氦是 MRI 機器的冷卻劑。",
            uses_en: "Used in balloons, airships, diving gas mixtures; liquid helium cools MRI machines.",
            fun_fact_zh: "氦氣是唯一在常壓下無法固化的元素，吸入後會讓聲音變高八度。",
            bg: "#ede0c8", color: "#776e65",
        }),
        E(3, "Li", "Lithium", "鋰", 2, 1, "alkali_metal", {
            atomic_weight: 6.94, electron_config: "[He] 2s¹", electronegativity: 0.98,
            melting_pt: 453.65, boiling_pt: 1603, state_at_stp: "solid",
            discovery_year: 1817, discoverer: "Johan August Arfwedson",
            uses_zh: "鋰電池廣泛用於手機、筆電、電動車；碳酸鋰用於治療躁鬱症。",
            uses_en: "Lithium-ion batteries power phones, laptops, EVs; lithium carbonate treats bipolar disorder.",
            fun_fact_zh: "鋰是最輕的金屬，密度只有水的一半，可以浮在水上但會劇烈反應。",
            bg: "#f2b179", color: "#f9f6f2",
        }),
        E(4, "Be", "Beryllium", "鈹", 2, 2, "alkaline_earth", {
            atomic_weight: 9.012, electron_config: "[He] 2s²", electronegativity: 1.57,
            melting_pt: 1560, boiling_pt: 2742, state_at_stp: "solid",
            discovery_year: 1798, discoverer: "Louis Nicolas Vauquelin",
            uses_zh: "鈹銅合金用於航太、核反應爐窗口；綠寶石和海藍寶石都含鈹。",
            uses_en: "Beryllium-copper alloys in aerospace, nuclear reactor windows; emeralds and aquamarines contain beryllium.",
            fun_fact_zh: "鈹的粉塵有劇毒會引起鈹中毒病；它對 X 射線幾乎透明。",
            bg: "#f59563", color: "#f9f6f2",
        }),
        E(5, "B", "Boron", "硼", 2, 13, "metalloid", {
            atomic_weight: 10.81, electron_config: "[He] 2s² 2p¹", electronegativity: 2.04,
            melting_pt: 2349, boiling_pt: 4200, state_at_stp: "solid",
            discovery_year: 1808, discoverer: "Joseph Louis Gay-Lussac",
            uses_zh: "硼砂用於洗滌劑、玻璃；硼酸是溫和殺菌劑；硼纖維是航太材料。",
            uses_en: "Borax in detergents and glass; boric acid as mild antiseptic; boron fiber in aerospace.",
            fun_fact_zh: "硼是植物必需的微量元素，缺硼會讓作物畸形。",
            bg: "#f67c5f", color: "#f9f6f2",
        }),
        E(6, "C", "Carbon", "碳", 2, 14, "nonmetal", {
            atomic_weight: 12.011, electron_config: "[He] 2s² 2p²", electronegativity: 2.55,
            melting_pt: 3823, boiling_pt: 4098, state_at_stp: "solid",
            discovery_year: null, discoverer: "Prehistoric",
            uses_zh: "碳是所有生命的基礎；煤、石油、鑽石、石墨、石墨烯都是碳的形式。",
            uses_en: "Foundation of all life; coal, oil, diamond, graphite, graphene are all forms of carbon.",
            fun_fact_zh: "鑽石和石墨都是純碳，但結構不同 — 一個是世界最硬，一個非常軟。",
            bg: "#f65e3b", color: "#f9f6f2",
        }),
        E(7, "N", "Nitrogen", "氮", 2, 15, "nonmetal", {
            atomic_weight: 14.007, electron_config: "[He] 2s² 2p³", electronegativity: 3.04,
            melting_pt: 63.15, boiling_pt: 77.36, state_at_stp: "gas",
            discovery_year: 1772, discoverer: "Daniel Rutherford",
            uses_zh: "氮氣佔大氣 78%；氨是氮肥的基礎；液態氮用於冷凍保存。",
            uses_en: "78% of atmosphere; ammonia is base of nitrogen fertilizers; liquid nitrogen for cryopreservation.",
            fun_fact_zh: "閃電會把氮氣固定成天然肥料降到土壤裡。",
            bg: "#edcf72", color: "#f9f6f2",
        }),
        E(8, "O", "Oxygen", "氧", 2, 16, "nonmetal", {
            atomic_weight: 15.999, electron_config: "[He] 2s² 2p⁴", electronegativity: 3.44,
            melting_pt: 54.36, boiling_pt: 90.20, state_at_stp: "gas",
            discovery_year: 1774, discoverer: "Joseph Priestley",
            uses_zh: "呼吸必需；煉鋼、醫療、火箭推進劑；臭氧層保護地球免受紫外線。",
            uses_en: "Essential for respiration; steelmaking, medical use, rocket propellant; ozone layer shields UV.",
            fun_fact_zh: "地殼中最豐富的元素 (46%)，海水中 88% 是氧。",
            bg: "#edcc61", color: "#f9f6f2",
        }),
        E(9, "F", "Fluorine", "氟", 2, 17, "halogen", {
            atomic_weight: 18.998, electron_config: "[He] 2s² 2p⁵", electronegativity: 3.98,
            melting_pt: 53.48, boiling_pt: 85.03, state_at_stp: "gas",
            discovery_year: 1886, discoverer: "Henri Moissan",
            uses_zh: "牙膏中的氟化物可預防蛀牙；鐵氟龍 (PTFE) 是不沾鍋塗層；製冷劑。",
            uses_en: "Fluoride in toothpaste prevents cavities; PTFE (Teflon) coats non-stick pans; refrigerants.",
            fun_fact_zh: "氟是電負度最強的元素，幾乎能氧化所有其他元素。",
            bg: "#edc850", color: "#f9f6f2",
        }),
        E(10, "Ne", "Neon", "氖", 2, 18, "noble_gas", {
            atomic_weight: 20.180, electron_config: "[He] 2s² 2p⁶", electronegativity: null,
            melting_pt: 24.56, boiling_pt: 27.07, state_at_stp: "gas",
            discovery_year: 1898, discoverer: "William Ramsay",
            uses_zh: "霓虹燈標誌、高壓指示燈、雷射、低溫致冷。",
            uses_en: "Neon signs, high-voltage indicators, lasers, cryogenic refrigerant.",
            fun_fact_zh: "通電的氖燈發出獨特的橙紅色光，是霓虹燈名字的由來。",
            bg: "#edc53f", color: "#f9f6f2",
        }),
        E(11, "Na", "Sodium", "鈉", 3, 1, "alkali_metal", {
            atomic_weight: 22.990, electron_config: "[Ne] 3s¹", electronegativity: 0.93,
            melting_pt: 370.87, boiling_pt: 1156, state_at_stp: "solid",
            discovery_year: 1807, discoverer: "Humphry Davy",
            uses_zh: "食鹽 (NaCl) 是主要來源；鈉燈、肥皂、玻璃、紙張製造。",
            uses_en: "Salt (NaCl) is main source; sodium lamps, soap, glass, paper manufacturing.",
            fun_fact_zh: "純鈉遇水會劇烈反應產生氫氣並燃燒，所以儲存在煤油中。",
            bg: "#edc22e", color: "#f9f6f2",
        }),
        E(12, "Mg", "Magnesium", "鎂", 3, 2, "alkaline_earth", {
            atomic_weight: 24.305, electron_config: "[Ne] 3s²", electronegativity: 1.31,
            melting_pt: 923, boiling_pt: 1363, state_at_stp: "solid",
            discovery_year: 1755, discoverer: "Joseph Black",
            uses_zh: "輕量合金 (用於汽車、飛機、筆電外殼)；煙火的銀白色光；葉綠素中心。",
            uses_en: "Lightweight alloys (cars, planes, laptops); silver-white sparks in fireworks; core of chlorophyll.",
            fun_fact_zh: "燃燒中的鎂發出極亮白光，過去用作相機閃光燈。",
            bg: "#3c3a32", color: "#f9f6f2",
        }),
        E(13, "Al", "Aluminum", "鋁", 3, 13, "post_transition", {
            atomic_weight: 26.982, electron_config: "[Ne] 3s² 3p¹", electronegativity: 1.61,
            melting_pt: 933.47, boiling_pt: 2792, state_at_stp: "solid",
            discovery_year: 1825, discoverer: "Hans Christian Ørsted",
            uses_zh: "飲料罐、鋁箔、飛機機身、電線；最常用的有色金屬。",
            uses_en: "Beverage cans, foil, airplane bodies, electrical wires; most common non-ferrous metal.",
            fun_fact_zh: "1850 年代鋁比黃金還珍貴，拿破崙三世只用鋁餐具招待最尊貴的客人。",
            bg: "#5fa3cc", color: "#f9f6f2",
        }),
        E(14, "Si", "Silicon", "矽", 3, 14, "metalloid", {
            atomic_weight: 28.085, electron_config: "[Ne] 3s² 3p²", electronegativity: 1.90,
            melting_pt: 1687, boiling_pt: 3538, state_at_stp: "solid",
            discovery_year: 1824, discoverer: "Jöns Jacob Berzelius",
            uses_zh: "晶片、太陽能板、玻璃、矽膠；現代電子工業的根本。",
            uses_en: "Computer chips, solar panels, glass, silicone; foundation of modern electronics.",
            fun_fact_zh: "「矽谷」的名字來自半導體晶片，地殼第二多的元素。",
            bg: "#4a8a99", color: "#f9f6f2",
        }),
        E(15, "P", "Phosphorus", "磷", 3, 15, "nonmetal", {
            atomic_weight: 30.974, electron_config: "[Ne] 3s² 3p³", electronegativity: 2.19,
            melting_pt: 317.30, boiling_pt: 553.65, state_at_stp: "solid",
            discovery_year: 1669, discoverer: "Hennig Brand",
            uses_zh: "磷肥、火柴、洗滌劑、DNA/RNA 骨架、ATP (生物能量分子)。",
            uses_en: "Fertilizer, matches, detergents, DNA/RNA backbone, ATP (biological energy).",
            fun_fact_zh: "白磷在空氣中會自燃發綠光，名字來自希臘文「光的攜帶者」。",
            bg: "#7bb38d", color: "#f9f6f2",
        }),
        E(16, "S", "Sulfur", "硫", 3, 16, "nonmetal", {
            atomic_weight: 32.06, electron_config: "[Ne] 3s² 3p⁴", electronegativity: 2.58,
            melting_pt: 388.36, boiling_pt: 717.87, state_at_stp: "solid",
            discovery_year: null, discoverer: "Prehistoric",
            uses_zh: "硫酸 (工業之母)、火藥、硫化橡膠、農藥；蛋白質中的胺基酸。",
            uses_en: "Sulfuric acid (mother of industry), gunpowder, vulcanized rubber, pesticides; in amino acids.",
            fun_fact_zh: "硫黃溫泉的臭味來自硫化氫，俗稱「臭蛋味」。",
            bg: "#a8c256", color: "#f9f6f2",
        }),
        E(17, "Cl", "Chlorine", "氯", 3, 17, "halogen", {
            atomic_weight: 35.45, electron_config: "[Ne] 3s² 3p⁵", electronegativity: 3.16,
            melting_pt: 171.65, boiling_pt: 239.11, state_at_stp: "gas",
            discovery_year: 1774, discoverer: "Carl Wilhelm Scheele",
            uses_zh: "自來水消毒、漂白劑、PVC 塑膠、食鹽 (NaCl) 的一半。",
            uses_en: "Water disinfection, bleach, PVC plastic, half of table salt (NaCl).",
            fun_fact_zh: "一戰中第一次被當作毒氣使用 (1915 伊普爾戰役)。",
            bg: "#8a9e40", color: "#f9f6f2",
        }),
        E(18, "Ar", "Argon", "氬", 3, 18, "noble_gas", {
            atomic_weight: 39.948, electron_config: "[Ne] 3s² 3p⁶", electronegativity: null,
            melting_pt: 83.80, boiling_pt: 87.30, state_at_stp: "gas",
            discovery_year: 1894, discoverer: "Lord Rayleigh",
            uses_zh: "白熾燈泡填充氣 (防鎢絲氧化)、焊接保護氣、雙層玻璃隔熱。",
            uses_en: "Light bulb fill (prevents tungsten oxidation), welding shield gas, insulating window gas.",
            fun_fact_zh: "氬佔大氣 0.93%，是大氣中第三多的氣體 (僅次氮、氧)。",
            bg: "#a37ebd", color: "#f9f6f2",
        }),
        E(19, "K", "Potassium", "鉀", 4, 1, "alkali_metal", {
            atomic_weight: 39.098, electron_config: "[Ar] 4s¹", electronegativity: 0.82,
            melting_pt: 336.53, boiling_pt: 1032, state_at_stp: "solid",
            discovery_year: 1807, discoverer: "Humphry Davy",
            uses_zh: "鉀肥 (植物生長必需)；人體神經傳導關鍵元素；香蕉富含鉀。",
            uses_en: "Potash fertilizer; essential for plant growth and nerve impulses; bananas are rich in K.",
            fun_fact_zh: "純鉀遇水比鈉更猛烈反應，會發出紫色火焰。",
            bg: "#8f57a6", color: "#f9f6f2",
        }),
        E(20, "Ca", "Calcium", "鈣", 4, 2, "alkaline_earth", {
            atomic_weight: 40.078, electron_config: "[Ar] 4s²", electronegativity: 1.00,
            melting_pt: 1115, boiling_pt: 1757, state_at_stp: "solid",
            discovery_year: 1808, discoverer: "Humphry Davy",
            uses_zh: "骨骼和牙齒的主成分；水泥、石灰石、大理石；牛奶富含鈣。",
            uses_en: "Main component of bones and teeth; cement, limestone, marble; milk is rich in calcium.",
            fun_fact_zh: "成人體內約 1 公斤鈣，99% 在骨骼和牙齒。",
            bg: "#5c336e", color: "#f9f6f2",
        }),

        // ── Period 4 (21-36) ──────────────────────────────────────
        E(21, "Sc", "Scandium", "鈧", 4, 3, "transition_metal", {
            atomic_weight: 44.956, electron_config: "[Ar] 3d¹ 4s²", electronegativity: 1.36,
            melting_pt: 1814, boiling_pt: 3109, state_at_stp: "solid",
            discovery_year: 1879, discoverer: "Lars Fredrik Nilson",
            uses_zh: "鋁鈧合金用於高級腳踏車、棒球棒；金屬鹵化物燈的添加劑。",
            uses_en: "Aluminum-scandium alloys in bicycles, baseball bats; metal halide lamps.",
            fun_fact_zh: "門得列夫早在 1869 年就預測了鈧的存在，10 年後才被發現。",
        }),
        E(22, "Ti", "Titanium", "鈦", 4, 4, "transition_metal", {
            atomic_weight: 47.867, electron_config: "[Ar] 3d² 4s²", electronegativity: 1.54,
            melting_pt: 1941, boiling_pt: 3560, state_at_stp: "solid",
            discovery_year: 1791, discoverer: "William Gregor",
            uses_zh: "醫療植入物 (人工關節、骨釘)、飛機引擎、潛艇外殼；強度比重比鋼還高。",
            uses_en: "Medical implants (joints, screws), jet engines, submarines; strength-to-weight ratio higher than steel.",
            fun_fact_zh: "鈦在海水中幾乎不腐蝕，所以用來做深海器材。",
        }),
        E(23, "V", "Vanadium", "釩", 4, 5, "transition_metal", {
            atomic_weight: 50.942, electron_config: "[Ar] 3d³ 4s²", electronegativity: 1.63,
            melting_pt: 2183, boiling_pt: 3680, state_at_stp: "solid",
            discovery_year: 1801, discoverer: "Andrés Manuel del Río",
            uses_zh: "釩鋼合金 (極堅硬，用於工具鋼、彈簧)；釩液流電池儲能。",
            uses_en: "Vanadium steel (extra hard, for tools and springs); vanadium flow batteries for energy storage.",
            fun_fact_zh: "釩的化合物有五種顏色 (對應 +2 ~ +5 氧化態)，化學課常用作展示。",
        }),
        E(24, "Cr", "Chromium", "鉻", 4, 6, "transition_metal", {
            atomic_weight: 51.996, electron_config: "[Ar] 3d⁵ 4s¹", electronegativity: 1.66,
            melting_pt: 2180, boiling_pt: 2944, state_at_stp: "solid",
            discovery_year: 1797, discoverer: "Louis Nicolas Vauquelin",
            uses_zh: "電鍍 (汽車保險桿、水龍頭的閃亮鍍層)；不鏽鋼必需成分；紅寶石的紅色。",
            uses_en: "Electroplating (chrome bumpers, faucets); essential for stainless steel; gives rubies their red.",
            fun_fact_zh: "「Chromium」源自希臘文「顏色」，因為它的化合物色彩繽紛。",
        }),
        E(25, "Mn", "Manganese", "錳", 4, 7, "transition_metal", {
            atomic_weight: 54.938, electron_config: "[Ar] 3d⁵ 4s²", electronegativity: 1.55,
            melting_pt: 1519, boiling_pt: 2334, state_at_stp: "solid",
            discovery_year: 1774, discoverer: "Johan Gottlieb Gahn",
            uses_zh: "鋼鐵合金 (增加硬度與抗磨)；乾電池的正極材料；高錳酸鉀消毒劑。",
            uses_en: "Steel alloys (hardness, wear resistance); cathode of dry cells; potassium permanganate disinfectant.",
            fun_fact_zh: "海床上有大量錳結核，是未來深海採礦的目標。",
        }),
        E(26, "Fe", "Iron", "鐵", 4, 8, "transition_metal", {
            atomic_weight: 55.845, electron_config: "[Ar] 3d⁶ 4s²", electronegativity: 1.83,
            melting_pt: 1811, boiling_pt: 3134, state_at_stp: "solid",
            discovery_year: null, discoverer: "Prehistoric",
            uses_zh: "建築鋼筋、橋樑、汽車、船舶；血紅蛋白攜帶氧氣的關鍵。",
            uses_en: "Construction steel, bridges, cars, ships; hemoglobin uses iron to carry oxygen.",
            fun_fact_zh: "地球的核心主要是鐵和鎳，產生了保護我們的磁場。",
        }),
        E(27, "Co", "Cobalt", "鈷", 4, 9, "transition_metal", {
            atomic_weight: 58.933, electron_config: "[Ar] 3d⁷ 4s²", electronegativity: 1.88,
            melting_pt: 1768, boiling_pt: 3200, state_at_stp: "solid",
            discovery_year: 1735, discoverer: "Georg Brandt",
            uses_zh: "鋰電池正極材料、磁鐵、藍色玻璃顏料；維生素 B12 的中心元素。",
            uses_en: "Lithium-ion battery cathodes, magnets, blue glass pigment; central atom of vitamin B12.",
            fun_fact_zh: "「鈷藍」是古代陶瓷和藝術中珍貴的藍色顏料。",
        }),
        E(28, "Ni", "Nickel", "鎳", 4, 10, "transition_metal", {
            atomic_weight: 58.693, electron_config: "[Ar] 3d⁸ 4s²", electronegativity: 1.91,
            melting_pt: 1728, boiling_pt: 3186, state_at_stp: "solid",
            discovery_year: 1751, discoverer: "Axel Fredrik Cronstedt",
            uses_zh: "不鏽鋼合金、硬幣、充電電池 (NiMH)；催化氫化反應。",
            uses_en: "Stainless steel, coins, rechargeable batteries (NiMH); catalyzes hydrogenation.",
            fun_fact_zh: "美國 5 分硬幣 25% 是鎳，所以叫「nickel」。",
        }),
        E(29, "Cu", "Copper", "銅", 4, 11, "transition_metal", {
            atomic_weight: 63.546, electron_config: "[Ar] 3d¹⁰ 4s¹", electronegativity: 1.90,
            melting_pt: 1357.77, boiling_pt: 2835, state_at_stp: "solid",
            discovery_year: null, discoverer: "Prehistoric",
            uses_zh: "電線、水管、屋頂；青銅 (銅+錫)、黃銅 (銅+鋅)。",
            uses_en: "Electrical wiring, plumbing, roofing; bronze (Cu+Sn), brass (Cu+Zn).",
            fun_fact_zh: "自由女神像本來是亮銅色，氧化後變成現在的綠色。",
        }),
        E(30, "Zn", "Zinc", "鋅", 4, 12, "transition_metal", {
            atomic_weight: 65.38, electron_config: "[Ar] 3d¹⁰ 4s²", electronegativity: 1.65,
            melting_pt: 692.68, boiling_pt: 1180, state_at_stp: "solid",
            discovery_year: 1746, discoverer: "Andreas Sigismund Marggraf",
            uses_zh: "鍍鋅鋼 (防鏽)、乾電池負極、防曬乳氧化鋅；人體必需微量元素。",
            uses_en: "Galvanized steel (rust prevention), dry cell anodes, zinc oxide sunscreen; essential trace mineral.",
            fun_fact_zh: "缺鋅會降低味覺和免疫力，牡蠣是含鋅最高的食物。",
        }),
        E(31, "Ga", "Gallium", "鎵", 4, 13, "post_transition", {
            atomic_weight: 69.723, electron_config: "[Ar] 3d¹⁰ 4s² 4p¹", electronegativity: 1.81,
            melting_pt: 302.91, boiling_pt: 2477, state_at_stp: "solid",
            discovery_year: 1875, discoverer: "Paul-Émile Lecoq de Boisbaudran",
            uses_zh: "氮化鎵 (GaN) 用於 LED 燈、雷射、5G 充電器；溫度計液體 (取代水銀)。",
            uses_en: "Gallium nitride for LEDs, lasers, 5G chargers; thermometer fluid (mercury replacement).",
            fun_fact_zh: "鎵會在 30°C 融化，握在手中就會變成液體。",
        }),
        E(32, "Ge", "Germanium", "鍺", 4, 14, "metalloid", {
            atomic_weight: 72.630, electron_config: "[Ar] 3d¹⁰ 4s² 4p²", electronegativity: 2.01,
            melting_pt: 1211.40, boiling_pt: 3106, state_at_stp: "solid",
            discovery_year: 1886, discoverer: "Clemens Winkler",
            uses_zh: "光纖通訊、紅外線光學鏡頭、早期電晶體 (現在被矽取代)。",
            uses_en: "Fiber optics, infrared optics, early transistors (now replaced by silicon).",
            fun_fact_zh: "1947 年第一個電晶體就是用鍺做的，後來才被矽取代。",
        }),
        E(33, "As", "Arsenic", "砷", 4, 15, "metalloid", {
            atomic_weight: 74.922, electron_config: "[Ar] 3d¹⁰ 4s² 4p³", electronegativity: 2.18,
            melting_pt: 887, boiling_pt: 887, state_at_stp: "solid",
            discovery_year: 1250, discoverer: "Albertus Magnus",
            uses_zh: "半導體 (砷化鎵)、農藥、木材防腐 (現已禁用)；劇毒。",
            uses_en: "Semiconductors (GaAs), pesticides, wood preservatives (now banned); highly toxic.",
            fun_fact_zh: "歷史上常被當作謀殺毒藥，因為無色無味又難以察覺。",
        }),
        E(34, "Se", "Selenium", "硒", 4, 16, "nonmetal", {
            atomic_weight: 78.971, electron_config: "[Ar] 3d¹⁰ 4s² 4p⁴", electronegativity: 2.55,
            melting_pt: 494, boiling_pt: 958, state_at_stp: "solid",
            discovery_year: 1817, discoverer: "Jöns Jacob Berzelius",
            uses_zh: "光電池、影印機感光鼓、玻璃染色；人體必需微量元素 (抗氧化)。",
            uses_en: "Photocells, photocopier drums, glass coloring; essential trace element (antioxidant).",
            fun_fact_zh: "硒對光敏感，是早期影印機和太陽能電池的關鍵材料。",
        }),
        E(35, "Br", "Bromine", "溴", 4, 17, "halogen", {
            atomic_weight: 79.904, electron_config: "[Ar] 3d¹⁰ 4s² 4p⁵", electronegativity: 2.96,
            melting_pt: 265.95, boiling_pt: 332.0, state_at_stp: "liquid",
            discovery_year: 1826, discoverer: "Antoine Jérôme Balard",
            uses_zh: "阻燃劑、攝影顯影劑、消毒劑、燃料添加劑。",
            uses_en: "Flame retardants, photographic developers, disinfectants, fuel additives.",
            fun_fact_zh: "溴是常溫常壓下唯一的液態非金屬，紅棕色而且劇臭。",
        }),
        E(36, "Kr", "Krypton", "氪", 4, 18, "noble_gas", {
            atomic_weight: 83.798, electron_config: "[Ar] 3d¹⁰ 4s² 4p⁶", electronegativity: 3.00,
            melting_pt: 115.78, boiling_pt: 119.93, state_at_stp: "gas",
            discovery_year: 1898, discoverer: "William Ramsay",
            uses_zh: "高效閃光燈、鐳射、霓虹燈 (產生白光)；舊定義公尺的標準波長。",
            uses_en: "High-output flash lamps, lasers, neon tubes (white light); used to define the meter (1960-1983).",
            fun_fact_zh: "1960 年到 1983 年，1 公尺被定義為氪-86 發出特定波長光的 1,650,763.73 倍。",
        }),

        // ── Period 5 (37-54) ──────────────────────────────────────
        E(37, "Rb", "Rubidium", "銣", 5, 1, "alkali_metal", {
            atomic_weight: 85.468, electron_config: "[Kr] 5s¹", electronegativity: 0.82,
            melting_pt: 312.46, boiling_pt: 961, state_at_stp: "solid",
            discovery_year: 1861, discoverer: "Robert Bunsen",
            uses_zh: "原子鐘、特殊玻璃、煙火 (紫紅色)。",
            uses_en: "Atomic clocks, specialty glass, fireworks (purple-red).",
            fun_fact_zh: "銣是第二活潑的鹼金屬 (僅次於銫)，遇水會爆炸。",
        }),
        E(38, "Sr", "Strontium", "鍶", 5, 2, "alkaline_earth", {
            atomic_weight: 87.62, electron_config: "[Kr] 5s²", electronegativity: 0.95,
            melting_pt: 1050, boiling_pt: 1655, state_at_stp: "solid",
            discovery_year: 1790, discoverer: "Adair Crawford",
            uses_zh: "煙火紅色光、舊式 CRT 電視玻璃、夜光塗料。",
            uses_en: "Red fireworks, old CRT TV glass, glow-in-the-dark paint.",
            fun_fact_zh: "煙火中的鮮紅色幾乎都是鍶化合物產生的。",
        }),
        E(39, "Y", "Yttrium", "釔", 5, 3, "transition_metal", {
            atomic_weight: 88.906, electron_config: "[Kr] 4d¹ 5s²", electronegativity: 1.22,
            melting_pt: 1799, boiling_pt: 3609, state_at_stp: "solid",
            discovery_year: 1794, discoverer: "Johan Gadolin",
            uses_zh: "LED 螢光體 (紅色)、超導體 (YBCO)、雷射晶體。",
            uses_en: "LED phosphors (red), high-temperature superconductors (YBCO), laser crystals.",
            fun_fact_zh: "瑞典小鎮 Ytterby 一地就發現了 4 個元素 (Y, Yb, Tb, Er)。",
        }),
        E(40, "Zr", "Zirconium", "鋯", 5, 4, "transition_metal", {
            atomic_weight: 91.224, electron_config: "[Kr] 4d² 5s²", electronegativity: 1.33,
            melting_pt: 2128, boiling_pt: 4682, state_at_stp: "solid",
            discovery_year: 1789, discoverer: "Martin Heinrich Klaproth",
            uses_zh: "核反應爐燃料棒外殼 (耐熱耐腐蝕)、人工關節、立方氧化鋯 (假鑽石)。",
            uses_en: "Nuclear fuel rod cladding (heat/corrosion resistant), joint replacements, cubic zirconia (fake diamond).",
            fun_fact_zh: "立方氧化鋯外觀和折射率與鑽石幾乎相同，常被當作鑽石替代品。",
        }),
        E(41, "Nb", "Niobium", "鈮", 5, 5, "transition_metal", {
            atomic_weight: 92.906, electron_config: "[Kr] 4d⁴ 5s¹", electronegativity: 1.6,
            melting_pt: 2750, boiling_pt: 5017, state_at_stp: "solid",
            discovery_year: 1801, discoverer: "Charles Hatchett",
            uses_zh: "高強度鋼合金、超導磁鐵 (MRI、粒子加速器)、首飾。",
            uses_en: "High-strength steel alloys, superconducting magnets (MRI, particle accelerators), jewelry.",
            fun_fact_zh: "鈮原本叫 Columbium，後來改名為 Niobium (希臘神話角色)。",
        }),
        E(42, "Mo", "Molybdenum", "鉬", 5, 6, "transition_metal", {
            atomic_weight: 95.95, electron_config: "[Kr] 4d⁵ 5s¹", electronegativity: 2.16,
            melting_pt: 2896, boiling_pt: 4912, state_at_stp: "solid",
            discovery_year: 1781, discoverer: "Peter Jacob Hjelm",
            uses_zh: "高溫鋼合金、潤滑劑 (二硫化鉬)、催化劑；植物固氮酶必需。",
            uses_en: "High-temp steel alloys, lubricants (MoS2), catalysts; essential for nitrogen fixation in plants.",
            fun_fact_zh: "鉬的熔點 2623°C 是常見金屬中第六高。",
        }),
        E(43, "Tc", "Technetium", "鎝", 5, 7, "transition_metal", {
            atomic_weight: 98, electron_config: "[Kr] 4d⁵ 5s²", electronegativity: 1.9,
            melting_pt: 2430, boiling_pt: 4538, state_at_stp: "solid",
            discovery_year: 1937, discoverer: "Carlo Perrier & Emilio Segrè",
            uses_zh: "醫學造影 (鎝-99m 是最常用的醫用同位素)；地球上幾乎不存在。",
            uses_en: "Medical imaging (Tc-99m is the most-used medical isotope); essentially nonexistent on Earth.",
            fun_fact_zh: "鎝是第一個被人工合成的元素 (1937)，名字源自希臘文「人造」。",
        }),
        E(44, "Ru", "Ruthenium", "釕", 5, 8, "transition_metal", {
            atomic_weight: 101.07, electron_config: "[Kr] 4d⁷ 5s¹", electronegativity: 2.2,
            melting_pt: 2607, boiling_pt: 4423, state_at_stp: "solid",
            discovery_year: 1844, discoverer: "Karl Ernst Claus",
            uses_zh: "硬碟塗層、燃料電池催化劑、太陽能電池；鉑合金硬化劑。",
            uses_en: "Hard disk coatings, fuel cell catalysts, solar cells; hardener for platinum alloys.",
            fun_fact_zh: "硬碟容量近 20 年大幅提升，部分歸功於釕薄膜的應用。",
        }),
        E(45, "Rh", "Rhodium", "銠", 5, 9, "transition_metal", {
            atomic_weight: 102.906, electron_config: "[Kr] 4d⁸ 5s¹", electronegativity: 2.28,
            melting_pt: 2237, boiling_pt: 3968, state_at_stp: "solid",
            discovery_year: 1803, discoverer: "William Hyde Wollaston",
            uses_zh: "汽車三元觸媒轉換器 (淨化廢氣)、白金首飾鍍層；最貴重的金屬之一。",
            uses_en: "Catalytic converters (cleans car exhaust), white gold plating; one of the most expensive metals.",
            fun_fact_zh: "2021 年銠價曾高達每盎司 29,000 美元，比黃金貴 14 倍。",
        }),
        E(46, "Pd", "Palladium", "鈀", 5, 10, "transition_metal", {
            atomic_weight: 106.42, electron_config: "[Kr] 4d¹⁰", electronegativity: 2.20,
            melting_pt: 1828.05, boiling_pt: 3236, state_at_stp: "solid",
            discovery_year: 1803, discoverer: "William Hyde Wollaston",
            uses_zh: "汽車催化轉換器、氫氣淨化、牙科填充材料；可吸附 900 倍體積的氫氣。",
            uses_en: "Catalytic converters, hydrogen purification, dental fillings; absorbs 900× its volume in hydrogen.",
            fun_fact_zh: "鈀對氫的吸附力極強，被用於儲氫材料的研究。",
        }),
        E(47, "Ag", "Silver", "銀", 5, 11, "transition_metal", {
            atomic_weight: 107.868, electron_config: "[Kr] 4d¹⁰ 5s¹", electronegativity: 1.93,
            melting_pt: 1234.93, boiling_pt: 2435, state_at_stp: "solid",
            discovery_year: null, discoverer: "Prehistoric",
            uses_zh: "首飾、餐具、貨幣；最佳導電與導熱金屬；攝影底片、抗菌塗層。",
            uses_en: "Jewelry, cutlery, currency; best electrical/thermal conductor; photographic film, antibacterial coatings.",
            fun_fact_zh: "銀是所有金屬中導電性最好的，但因為價格高所以多用銅作電線。",
        }),
        E(48, "Cd", "Cadmium", "鎘", 5, 12, "transition_metal", {
            atomic_weight: 112.414, electron_config: "[Kr] 4d¹⁰ 5s²", electronegativity: 1.69,
            melting_pt: 594.22, boiling_pt: 1040, state_at_stp: "solid",
            discovery_year: 1817, discoverer: "Friedrich Stromeyer",
            uses_zh: "鎳鎘充電電池、黃色顏料、太陽能電池；劇毒，現多被取代。",
            uses_en: "NiCd rechargeable batteries, yellow pigments, solar cells; highly toxic, being phased out.",
            fun_fact_zh: "鎘中毒會引起「痛痛病」，1950 年代日本因鎘污染河川造成大量受害者。",
        }),
        E(49, "In", "Indium", "銦", 5, 13, "post_transition", {
            atomic_weight: 114.818, electron_config: "[Kr] 4d¹⁰ 5s² 5p¹", electronegativity: 1.78,
            melting_pt: 429.75, boiling_pt: 2345, state_at_stp: "solid",
            discovery_year: 1863, discoverer: "Ferdinand Reich",
            uses_zh: "觸控螢幕的透明導電膜 (ITO)、LCD 螢幕、低熔點焊料。",
            uses_en: "Transparent conductive coatings on touchscreens (ITO), LCD displays, low-melt solder.",
            fun_fact_zh: "你的手機螢幕能觸控，幾乎全靠氧化銦錫 (ITO) 這層透明導體。",
        }),
        E(50, "Sn", "Tin", "錫", 5, 14, "post_transition", {
            atomic_weight: 118.710, electron_config: "[Kr] 4d¹⁰ 5s² 5p²", electronegativity: 1.96,
            melting_pt: 505.08, boiling_pt: 2875, state_at_stp: "solid",
            discovery_year: null, discoverer: "Prehistoric",
            uses_zh: "焊料、罐頭塗層 (馬口鐵)、青銅 (銅+錫)、玻璃製造。",
            uses_en: "Solder, tin cans (tin-coated steel), bronze (copper+tin), glass manufacturing.",
            fun_fact_zh: "「錫疫」現象：低溫下白錫會變成易碎的灰錫粉末，1812 年拿破崙的軍服紐扣就因此崩解。",
        }),
        E(51, "Sb", "Antimony", "銻", 5, 15, "metalloid", {
            atomic_weight: 121.760, electron_config: "[Kr] 4d¹⁰ 5s² 5p³", electronegativity: 2.05,
            melting_pt: 903.78, boiling_pt: 1860, state_at_stp: "solid",
            discovery_year: 1540, discoverer: "Vannoccio Biringuccio",
            uses_zh: "鉛酸電池合金、阻燃劑、半導體 (紅外線偵測器)。",
            uses_en: "Lead-acid battery alloys, flame retardants, infrared detector semiconductors.",
            fun_fact_zh: "古埃及人用銻硫化物 (kohl) 做眼影，已有 4000 年歷史。",
        }),
        E(52, "Te", "Tellurium", "碲", 5, 16, "metalloid", {
            atomic_weight: 127.60, electron_config: "[Kr] 4d¹⁰ 5s² 5p⁴", electronegativity: 2.1,
            melting_pt: 722.66, boiling_pt: 1261, state_at_stp: "solid",
            discovery_year: 1782, discoverer: "Franz-Joseph Müller von Reichenstein",
            uses_zh: "薄膜太陽能電池 (CdTe)、橡膠硫化、合金。",
            uses_en: "Thin-film solar cells (CdTe), rubber vulcanization, alloys.",
            fun_fact_zh: "接觸碲的人會散發大蒜味，幾週都散不去。",
        }),
        E(53, "I", "Iodine", "碘", 5, 17, "halogen", {
            atomic_weight: 126.904, electron_config: "[Kr] 4d¹⁰ 5s² 5p⁵", electronegativity: 2.66,
            melting_pt: 386.85, boiling_pt: 457.4, state_at_stp: "solid",
            discovery_year: 1811, discoverer: "Bernard Courtois",
            uses_zh: "碘酒消毒、加碘鹽 (預防甲狀腺腫)、醫學造影對比劑。",
            uses_en: "Iodine antiseptic, iodized salt (prevents goiter), medical imaging contrast agent.",
            fun_fact_zh: "海帶富含碘，缺碘會導致甲狀腺腫大，這就是為什麼食鹽要加碘。",
        }),
        E(54, "Xe", "Xenon", "氙", 5, 18, "noble_gas", {
            atomic_weight: 131.293, electron_config: "[Kr] 4d¹⁰ 5s² 5p⁶", electronegativity: 2.6,
            melting_pt: 161.40, boiling_pt: 165.05, state_at_stp: "gas",
            discovery_year: 1898, discoverer: "William Ramsay",
            uses_zh: "汽車氙氣大燈、閃光燈、離子推進器、麻醉劑。",
            uses_en: "HID headlamps, flash lamps, ion thrusters, anesthetic.",
            fun_fact_zh: "氙是少數能形成化合物的稀有氣體，1962 年首次合成 XeF4 震驚化學界。",
        }),

        // ── Period 6 (55-86) ──────────────────────────────────────
        E(55, "Cs", "Caesium", "銫", 6, 1, "alkali_metal", {
            atomic_weight: 132.905, electron_config: "[Xe] 6s¹", electronegativity: 0.79,
            melting_pt: 301.59, boiling_pt: 944, state_at_stp: "solid",
            discovery_year: 1860, discoverer: "Robert Bunsen",
            uses_zh: "銫原子鐘 (定義 1 秒長度)、石油勘探鑽井液、電子真空管。",
            uses_en: "Cesium atomic clocks (define the second), oil drilling fluids, vacuum tubes.",
            fun_fact_zh: "1 秒被定義為銫-133 原子發射特定光波 9,192,631,770 次的時間。",
        }),
        E(56, "Ba", "Barium", "鋇", 6, 2, "alkaline_earth", {
            atomic_weight: 137.327, electron_config: "[Xe] 6s²", electronegativity: 0.89,
            melting_pt: 1000, boiling_pt: 2170, state_at_stp: "solid",
            discovery_year: 1808, discoverer: "Humphry Davy",
            uses_zh: "煙火綠色光、X 光鋇餐 (檢查腸胃)、鑽井泥漿；可溶鋇有毒。",
            uses_en: "Green fireworks, barium meal for GI X-rays, drilling mud; soluble barium is toxic.",
            fun_fact_zh: "硫酸鋇不溶於水所以無毒，是 X 光腸胃造影必喝的「鋇餐」。",
        }),
        // Lanthanides 57-71 (compact)
        E(57, "La", "Lanthanum", "鑭", 6, 3, "lanthanide", {
            atomic_weight: 138.905, electron_config: "[Xe] 5d¹ 6s²",
            melting_pt: 1193, boiling_pt: 3737, state_at_stp: "solid",
            discovery_year: 1839, discoverer: "Carl Gustaf Mosander",
            uses_zh: "鑭系元素之首；用於相機鏡頭高折射玻璃、打火石、油裂解催化劑。",
            uses_en: "First lanthanide; used in camera lenses, lighter flints, oil cracking catalysts.",
            fun_fact_zh: "「Lanthanum」希臘文意為「隱藏」，因為它躲在鈰礦中難以分離。",
        }),
        E(58, "Ce", "Cerium", "鈰", 6, null, "lanthanide", {
            atomic_weight: 140.116, electron_config: "[Xe] 4f¹ 5d¹ 6s²",
            melting_pt: 1068, boiling_pt: 3716, state_at_stp: "solid",
            discovery_year: 1803, discoverer: "Jöns Jakob Berzelius",
            uses_zh: "汽車催化轉換器、玻璃拋光粉、打火石；地殼中最豐富的鑭系元素。",
            uses_en: "Catalytic converters, glass polishing, lighter flints; most abundant lanthanide in crust.",
            fun_fact_zh: "鈰其實比錫和鉛還常見，但分離困難所以價格不菲。",
        }),
        E(59, "Pr", "Praseodymium", "鐠", 6, null, "lanthanide", {
            atomic_weight: 140.908, electron_config: "[Xe] 4f³ 6s²",
            melting_pt: 1208, boiling_pt: 3793, state_at_stp: "solid",
            discovery_year: 1885, discoverer: "Carl Auer von Welsbach",
            uses_zh: "強力磁鐵 (與釹合用)、護目鏡 (吸收強光)、玻璃黃綠色染料。",
            uses_en: "Strong magnets (with neodymium), welder's goggles (UV filter), yellow-green glass colorant.",
            fun_fact_zh: "「鐠」希臘文意為「綠色雙胞胎」，因為與釹一起被發現且氧化物呈綠色。",
        }),
        E(60, "Nd", "Neodymium", "釹", 6, null, "lanthanide", {
            atomic_weight: 144.242, electron_config: "[Xe] 4f⁴ 6s²",
            melting_pt: 1297, boiling_pt: 3347, state_at_stp: "solid",
            discovery_year: 1885, discoverer: "Carl Auer von Welsbach",
            uses_zh: "釹鐵硼磁鐵 (世界最強永久磁鐵)，用於耳機、硬碟、風力發電機。",
            uses_en: "Nd-Fe-B magnets (strongest permanent magnets), used in headphones, hard drives, wind turbines.",
            fun_fact_zh: "你的耳機之所以能做得很小聲音又響，靠的就是釹磁鐵。",
        }),
        E(61, "Pm", "Promethium", "鉕", 6, null, "lanthanide", {
            atomic_weight: 145, electron_config: "[Xe] 4f⁵ 6s²",
            melting_pt: 1315, boiling_pt: 3273, state_at_stp: "solid",
            discovery_year: 1945, discoverer: "Jacob A. Marinsky",
            uses_zh: "夜光錶盤、核電池、原子能研究；地球上幾乎不存在 (僅微量於鈾礦)。",
            uses_en: "Luminous watch dials, nuclear batteries, atomic research; essentially absent on Earth.",
            fun_fact_zh: "鉕是唯一一個地球上幾乎全靠人造的鑭系元素，因為所有同位素都有放射性。",
        }),
        E(62, "Sm", "Samarium", "釤", 6, null, "lanthanide", {
            atomic_weight: 150.36, electron_config: "[Xe] 4f⁶ 6s²",
            melting_pt: 1345, boiling_pt: 2067, state_at_stp: "solid",
            discovery_year: 1879, discoverer: "Lecoq de Boisbaudran",
            uses_zh: "釤鈷磁鐵 (耐高溫)、核反應爐控制棒、雷射晶體。",
            uses_en: "Samarium-cobalt magnets (heat-resistant), reactor control rods, laser crystals.",
            fun_fact_zh: "釤是第一個以人名命名的元素 (Vasili Samarsky-Bykhovets)。",
        }),
        E(63, "Eu", "Europium", "銪", 6, null, "lanthanide", {
            atomic_weight: 151.964, electron_config: "[Xe] 4f⁷ 6s²",
            melting_pt: 1099, boiling_pt: 1802, state_at_stp: "solid",
            discovery_year: 1901, discoverer: "Eugène-Anatole Demarçay",
            uses_zh: "歐元紙鈔的紅色螢光防偽、CRT 與 LED 螢幕的紅色螢光體。",
            uses_en: "Red phosphor in Euro banknote anti-counterfeiting; red phosphor in CRT and LED displays.",
            fun_fact_zh: "用紫外線照歐元紙鈔，紅色發光的部分就是銪化合物。",
        }),
        E(64, "Gd", "Gadolinium", "釓", 6, null, "lanthanide", {
            atomic_weight: 157.25, electron_config: "[Xe] 4f⁷ 5d¹ 6s²",
            melting_pt: 1585, boiling_pt: 3546, state_at_stp: "solid",
            discovery_year: 1880, discoverer: "Jean Charles Galissard de Marignac",
            uses_zh: "MRI 造影對比劑、核反應爐中子吸收劑、磁致冷技術。",
            uses_en: "MRI contrast agents, neutron absorbers in reactors, magnetic refrigeration.",
            fun_fact_zh: "釓有獨特的磁致冷效應，加磁場會升溫、去磁場會降溫。",
        }),
        E(65, "Tb", "Terbium", "鋱", 6, null, "lanthanide", {
            atomic_weight: 158.925, electron_config: "[Xe] 4f⁹ 6s²",
            melting_pt: 1629, boiling_pt: 3503, state_at_stp: "solid",
            discovery_year: 1843, discoverer: "Carl Gustaf Mosander",
            uses_zh: "綠色螢光體 (LED、CRT)、固態裝置、磁伸縮材料。",
            uses_en: "Green phosphor (LEDs, CRTs), solid-state devices, magnetostrictive materials.",
            fun_fact_zh: "你看 LED 螢幕的綠色像素，發光的就是含鋱化合物。",
        }),
        E(66, "Dy", "Dysprosium", "鏑", 6, null, "lanthanide", {
            atomic_weight: 162.500, electron_config: "[Xe] 4f¹⁰ 6s²",
            melting_pt: 1680, boiling_pt: 2840, state_at_stp: "solid",
            discovery_year: 1886, discoverer: "Lecoq de Boisbaudran",
            uses_zh: "電動車馬達 (耐高溫釹磁鐵添加)、核反應爐控制棒。",
            uses_en: "Electric vehicle motors (heat-tolerant Nd magnet additive), nuclear control rods.",
            fun_fact_zh: "「鏑」希臘文意為「難以取得」，因為它真的非常難分離。",
        }),
        E(67, "Ho", "Holmium", "鈥", 6, null, "lanthanide", {
            atomic_weight: 164.930, electron_config: "[Xe] 4f¹¹ 6s²",
            melting_pt: 1734, boiling_pt: 2993, state_at_stp: "solid",
            discovery_year: 1878, discoverer: "Marc Delafontaine",
            uses_zh: "醫療雷射 (擊碎結石)、核子反應爐控制棒；磁性最強的元素。",
            uses_en: "Medical lasers (kidney stones), nuclear control rods; strongest magnetic moment of any element.",
            fun_fact_zh: "鈥的磁矩是所有元素中最大的。",
        }),
        E(68, "Er", "Erbium", "鉺", 6, null, "lanthanide", {
            atomic_weight: 167.259, electron_config: "[Xe] 4f¹² 6s²",
            melting_pt: 1802, boiling_pt: 3141, state_at_stp: "solid",
            discovery_year: 1843, discoverer: "Carl Gustaf Mosander",
            uses_zh: "光纖通訊放大器 (鉺摻雜光纖)、雷射、玻璃粉紅染色。",
            uses_en: "Fiber-optic amplifiers (erbium-doped fiber), lasers, pink glass coloring.",
            fun_fact_zh: "全世界的長距離光纖網路都依賴鉺摻雜光纖放大器 (EDFA)。",
        }),
        E(69, "Tm", "Thulium", "銩", 6, null, "lanthanide", {
            atomic_weight: 168.934, electron_config: "[Xe] 4f¹³ 6s²",
            melting_pt: 1818, boiling_pt: 2223, state_at_stp: "solid",
            discovery_year: 1879, discoverer: "Per Teodor Cleve",
            uses_zh: "便攜 X 光機、雷射手術 (尤其前列腺)、固態雷射增益介質。",
            uses_en: "Portable X-ray machines, laser surgery (especially prostate), solid-state lasers.",
            fun_fact_zh: "銩是地殼中最稀有的天然鑭系元素之一。",
        }),
        E(70, "Yb", "Ytterbium", "鐿", 6, null, "lanthanide", {
            atomic_weight: 173.045, electron_config: "[Xe] 4f¹⁴ 6s²",
            melting_pt: 1097, boiling_pt: 1469, state_at_stp: "solid",
            discovery_year: 1878, discoverer: "Jean Charles Galissard de Marignac",
            uses_zh: "原子鐘 (比銫更精確)、不鏽鋼晶粒細化劑、雷射放大器。",
            uses_en: "Atomic clocks (more precise than cesium), stainless steel grain refiner, laser amplifiers.",
            fun_fact_zh: "鐿原子鐘的精度可達 10⁻¹⁸，相當於 138 億年才差 1 秒。",
        }),
        E(71, "Lu", "Lutetium", "鎦", 6, null, "lanthanide", {
            atomic_weight: 174.967, electron_config: "[Xe] 4f¹⁴ 5d¹ 6s²",
            melting_pt: 1925, boiling_pt: 3675, state_at_stp: "solid",
            discovery_year: 1907, discoverer: "Georges Urbain",
            uses_zh: "石油催化裂解、PET 醫學造影、LED 螢光體；最後一個鑭系元素。",
            uses_en: "Petroleum cracking catalysts, PET imaging, LED phosphors; last lanthanide.",
            fun_fact_zh: "鎦是密度最大、最硬的鑭系元素，也是最貴的稀土之一。",
        }),
        // Late period 6 transition metals
        E(72, "Hf", "Hafnium", "鉿", 6, 4, "transition_metal", {
            atomic_weight: 178.49, electron_config: "[Xe] 4f¹⁴ 5d² 6s²",
            melting_pt: 2506, boiling_pt: 4876, state_at_stp: "solid",
            discovery_year: 1923, discoverer: "Dirk Coster",
            uses_zh: "核反應爐控制棒、半導體製造 (高介電閘極氧化物)、超合金。",
            uses_en: "Nuclear control rods, semiconductor high-k gate oxides, superalloys.",
            fun_fact_zh: "Intel 45nm 製程的關鍵材料就是鉿基絕緣層。",
        }),
        E(73, "Ta", "Tantalum", "鉭", 6, 5, "transition_metal", {
            atomic_weight: 180.948, electron_config: "[Xe] 4f¹⁴ 5d³ 6s²",
            melting_pt: 3290, boiling_pt: 5731, state_at_stp: "solid",
            discovery_year: 1802, discoverer: "Anders Gustaf Ekeberg",
            uses_zh: "電容器 (手機、相機)、外科植入物、化學處理設備。",
            uses_en: "Capacitors (phones, cameras), surgical implants, chemical processing equipment.",
            fun_fact_zh: "幾乎每支智慧型手機都有鉭電容；剛果衝突礦物之一。",
        }),
        E(74, "W", "Tungsten", "鎢", 6, 6, "transition_metal", {
            atomic_weight: 183.84, electron_config: "[Xe] 4f¹⁴ 5d⁴ 6s²",
            melting_pt: 3695, boiling_pt: 5828, state_at_stp: "solid",
            discovery_year: 1783, discoverer: "Juan José & Fausto Elhuyar",
            uses_zh: "白熾燈絲、X 光機靶材、軍用穿甲彈、工具鋼；熔點最高的金屬。",
            uses_en: "Light bulb filaments, X-ray targets, armor-piercing ammunition, tool steel; highest melting point.",
            fun_fact_zh: "鎢的熔點 3422°C 是所有金屬中最高，所以用作燈泡燈絲。",
        }),
        E(75, "Re", "Rhenium", "錸", 6, 7, "transition_metal", {
            atomic_weight: 186.207, electron_config: "[Xe] 4f¹⁴ 5d⁵ 6s²",
            melting_pt: 3459, boiling_pt: 5869, state_at_stp: "solid",
            discovery_year: 1925, discoverer: "Walter Noddack",
            uses_zh: "噴射引擎渦輪葉片 (耐極高溫)、催化劑；最後一個被發現的穩定元素。",
            uses_en: "Jet engine turbine blades (extreme heat), catalysts; last stable element to be discovered.",
            fun_fact_zh: "錸是地殼中最稀有的元素之一，每年產量只有約 50 噸。",
        }),
        E(76, "Os", "Osmium", "鋨", 6, 8, "transition_metal", {
            atomic_weight: 190.23, electron_config: "[Xe] 4f¹⁴ 5d⁶ 6s²",
            melting_pt: 3306, boiling_pt: 5285, state_at_stp: "solid",
            discovery_year: 1803, discoverer: "Smithson Tennant",
            uses_zh: "鋼筆筆尖、留聲機唱針、電氣接點；密度最大的元素 (22.59 g/cm³)。",
            uses_en: "Fountain pen tips, phonograph needles, electrical contacts; densest element (22.59 g/cm³).",
            fun_fact_zh: "1 立方公分的鋨重 22.59 克，是水的 22 倍。",
        }),
        E(77, "Ir", "Iridium", "銥", 6, 9, "transition_metal", {
            atomic_weight: 192.217, electron_config: "[Xe] 4f¹⁴ 5d⁷ 6s²",
            melting_pt: 2719, boiling_pt: 4701, state_at_stp: "solid",
            discovery_year: 1803, discoverer: "Smithson Tennant",
            uses_zh: "火星塞電極、坩堝、特殊合金；地殼中極稀有但隕石中常見。",
            uses_en: "Spark plug electrodes, crucibles, specialty alloys; rare in crust but common in meteorites.",
            fun_fact_zh: "白堊紀末地層發現異常高的銥，是恐龍滅絕小行星撞擊的關鍵證據。",
        }),
        E(78, "Pt", "Platinum", "鉑", 6, 10, "transition_metal", {
            atomic_weight: 195.084, electron_config: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
            melting_pt: 2041.4, boiling_pt: 4098, state_at_stp: "solid",
            discovery_year: 1735, discoverer: "Antonio de Ulloa",
            uses_zh: "汽車催化轉換器、首飾、化學催化劑、實驗室器皿；俗稱白金。",
            uses_en: "Catalytic converters, jewelry, chemical catalysts, lab ware; commonly called 'white gold'.",
            fun_fact_zh: "全世界一半的鉑被用於汽車催化轉換器淨化廢氣。",
        }),
        E(79, "Au", "Gold", "金", 6, 11, "transition_metal", {
            atomic_weight: 196.967, electron_config: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
            melting_pt: 1337.33, boiling_pt: 3129, state_at_stp: "solid",
            discovery_year: null, discoverer: "Prehistoric",
            uses_zh: "首飾、貨幣、電子接點、牙科；化學上極穩定不易腐蝕。",
            uses_en: "Jewelry, currency, electronic contacts, dentistry; chemically inert and resistant to corrosion.",
            fun_fact_zh: "1 克黃金可以拉成 165 公尺長的金線，或打成 1 平方公尺的金箔。",
        }),
        E(80, "Hg", "Mercury", "汞", 6, 12, "transition_metal", {
            atomic_weight: 200.592, electron_config: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
            melting_pt: 234.32, boiling_pt: 629.88, state_at_stp: "liquid",
            discovery_year: null, discoverer: "Prehistoric",
            uses_zh: "舊式溫度計、氣壓計、螢光燈、牙科汞合金；俗稱水銀。",
            uses_en: "Old thermometers, barometers, fluorescent lamps, dental amalgam; commonly called quicksilver.",
            fun_fact_zh: "汞是常溫常壓下唯一的液態金屬，劇毒，過去帽匠用它鞣製毛氈導致中毒，所以才有「瘋帽子」一詞。",
        }),
        E(81, "Tl", "Thallium", "鉈", 6, 13, "post_transition", {
            atomic_weight: 204.38, electron_config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
            melting_pt: 577, boiling_pt: 1746, state_at_stp: "solid",
            discovery_year: 1861, discoverer: "William Crookes",
            uses_zh: "紅外線偵測器、低溫溫度計、心臟造影對比劑；劇毒、無味，曾是「完美毒藥」。",
            uses_en: "Infrared detectors, low-temp thermometers, cardiac imaging; tasteless poison, once 'perfect poison'.",
            fun_fact_zh: "鉈中毒會掉光頭髮，阿嘉莎·克莉絲蒂的小說《白馬酒館》就用它當謀殺工具。",
        }),
        E(82, "Pb", "Lead", "鉛", 6, 14, "post_transition", {
            atomic_weight: 207.2, electron_config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
            melting_pt: 600.61, boiling_pt: 2022, state_at_stp: "solid",
            discovery_year: null, discoverer: "Prehistoric",
            uses_zh: "鉛酸電池 (汽車啟動電池)、輻射屏蔽、子彈、舊管路；劇毒，現代多被取代。",
            uses_en: "Lead-acid batteries, radiation shielding, bullets, old pipes; toxic, being phased out.",
            fun_fact_zh: "古羅馬人用鉛管供水，許多歷史學家認為鉛中毒加速了羅馬帝國衰亡。",
        }),
        E(83, "Bi", "Bismuth", "鉍", 6, 15, "post_transition", {
            atomic_weight: 208.980, electron_config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
            melting_pt: 544.7, boiling_pt: 1837, state_at_stp: "solid",
            discovery_year: 1753, discoverer: "Claude François Geoffroy",
            uses_zh: "胃藥 (次水楊酸鉍)、低熔點合金、化妝品、無鉛子彈替代品。",
            uses_en: "Stomach medicine (Pepto-Bismol), low-melt alloys, cosmetics, lead-free shot.",
            fun_fact_zh: "鉍的結晶呈現美麗的彩虹色階梯狀，是化學課展示的人氣項目。",
        }),
        E(84, "Po", "Polonium", "釙", 6, 16, "post_transition", {
            atomic_weight: 209, electron_config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
            melting_pt: 527, boiling_pt: 1235, state_at_stp: "solid",
            discovery_year: 1898, discoverer: "Pierre & Marie Curie",
            uses_zh: "防靜電裝置、衛星熱源、核武器引爆器；劇毒放射性，極少使用。",
            uses_en: "Anti-static devices, satellite heat sources, nuclear weapon initiators; highly radioactive.",
            fun_fact_zh: "瑪麗居禮以祖國波蘭命名了釙；2006 年俄國前特工 Litvinenko 就是被釙-210 毒死。",
        }),
        E(85, "At", "Astatine", "砈", 6, 17, "halogen", {
            atomic_weight: 210, electron_config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
            melting_pt: 575, boiling_pt: 610, state_at_stp: "solid",
            discovery_year: 1940, discoverer: "Dale R. Corson",
            uses_zh: "醫學研究 (癌症放射治療)；地球上總量不足 1 克，最稀有的天然元素。",
            uses_en: "Medical research (cancer radiotherapy); less than 1 gram total on Earth, rarest natural element.",
            fun_fact_zh: "砈半衰期只有 8.1 小時，全宇宙從未有人見過足以肉眼觀察的純砈樣本。",
        }),
        E(86, "Rn", "Radon", "氡", 6, 18, "noble_gas", {
            atomic_weight: 222, electron_config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
            melting_pt: 202, boiling_pt: 211.5, state_at_stp: "gas",
            discovery_year: 1900, discoverer: "Friedrich Ernst Dorn",
            uses_zh: "癌症放射治療 (歷史用法)、地震預警；房屋地下室中的氡是肺癌主因之一。",
            uses_en: "Historical cancer therapy, earthquake prediction; basement radon is a major lung cancer cause.",
            fun_fact_zh: "氡是無色無味的放射性氣體，從花崗岩釋放，是吸菸者以外肺癌的第二大原因。",
        }),

        // ── Period 7 (87-118) ─────────────────────────────────────
        E(87, "Fr", "Francium", "鍅", 7, 1, "alkali_metal", {
            atomic_weight: 223, electron_config: "[Rn] 7s¹",
            melting_pt: 300, boiling_pt: 950, state_at_stp: "solid",
            discovery_year: 1939, discoverer: "Marguerite Perey",
            uses_zh: "純科學研究；地球上任何時刻總量不超過 30 克；最不穩定的鹼金屬。",
            uses_en: "Pure research only; never more than 30 grams on Earth; most unstable alkali metal.",
            fun_fact_zh: "鍅以法國 (France) 命名；曾被視為最後一個天然元素。",
        }),
        E(88, "Ra", "Radium", "鐳", 7, 2, "alkaline_earth", {
            atomic_weight: 226, electron_config: "[Rn] 7s²",
            melting_pt: 973, boiling_pt: 2010, state_at_stp: "solid",
            discovery_year: 1898, discoverer: "Pierre & Marie Curie",
            uses_zh: "夜光錶盤 (歷史)、癌症放射治療 (現多被取代)；高度放射性，劇毒。",
            uses_en: "Glow-in-the-dark watch dials (historical), cancer radiotherapy (mostly replaced); highly radioactive.",
            fun_fact_zh: "1920 年代美國「鐳女郎」工廠工人因含口塗鐳發光顏料的筆而中毒死亡。",
        }),
        // Actinides 89-103 (compact)
        E(89, "Ac", "Actinium", "錒", 7, 3, "actinide", {
            atomic_weight: 227, electron_config: "[Rn] 6d¹ 7s²",
            melting_pt: 1323, boiling_pt: 3471, state_at_stp: "solid",
            discovery_year: 1899, discoverer: "André-Louis Debierne",
            uses_zh: "中子源、癌症 α 射線標靶治療；地殼中極微量。",
            uses_en: "Neutron sources, alpha-particle cancer therapy; extremely rare in crust.",
            fun_fact_zh: "錒的放射強度是鐳的 150 倍，在黑暗中發出淡藍光。",
        }),
        E(90, "Th", "Thorium", "釷", 7, null, "actinide", {
            atomic_weight: 232.038, electron_config: "[Rn] 6d² 7s²",
            melting_pt: 2115, boiling_pt: 5061, state_at_stp: "solid",
            discovery_year: 1828, discoverer: "Jöns Jakob Berzelius",
            uses_zh: "潛在替代核燃料 (釷反應爐)、合金硬化劑、舊式煤氣燈紗罩。",
            uses_en: "Potential nuclear fuel (thorium reactors), alloy hardener, old gas mantles.",
            fun_fact_zh: "釷反應爐被認為比鈾反應爐更安全，被視為未來核能方向。",
        }),
        E(91, "Pa", "Protactinium", "鏷", 7, null, "actinide", {
            atomic_weight: 231.036, electron_config: "[Rn] 5f² 6d¹ 7s²",
            melting_pt: 1841, boiling_pt: 4300, state_at_stp: "solid",
            discovery_year: 1913, discoverer: "Kasimir Fajans",
            uses_zh: "純科學研究；極稀有且劇毒，幾乎無實用價值。",
            uses_en: "Pure research only; extremely rare and toxic, no practical use.",
            fun_fact_zh: "鏷的名字意為「錒之前」，因為它衰變後會變成錒。",
        }),
        E(92, "U", "Uranium", "鈾", 7, null, "actinide", {
            atomic_weight: 238.029, electron_config: "[Rn] 5f³ 6d¹ 7s²",
            melting_pt: 1405.3, boiling_pt: 4404, state_at_stp: "solid",
            discovery_year: 1789, discoverer: "Martin Heinrich Klaproth",
            uses_zh: "核電廠燃料、核武器、軍用穿甲彈 (貧化鈾)、玻璃染色 (淡黃綠色)。",
            uses_en: "Nuclear reactor fuel, nuclear weapons, depleted uranium ammunition, glass coloring.",
            fun_fact_zh: "鈾-235 是唯一可以維持核連鎖反應的天然同位素，1945 年廣島原子彈用的就是它。",
        }),
        E(93, "Np", "Neptunium", "錼", 7, null, "actinide", {
            atomic_weight: 237, electron_config: "[Rn] 5f⁴ 6d¹ 7s²",
            melting_pt: 917, boiling_pt: 4273, state_at_stp: "solid",
            discovery_year: 1940, discoverer: "Edwin McMillan",
            uses_zh: "中子偵測儀器、核研究；第一個被人工合成的超鈾元素。",
            uses_en: "Neutron detection instruments, nuclear research; first synthesized transuranium element.",
            fun_fact_zh: "錼以海王星 (Neptune) 命名，因為它在週期表上接在鈾 (Uranus) 之後。",
        }),
        E(94, "Pu", "Plutonium", "鈽", 7, null, "actinide", {
            atomic_weight: 244, electron_config: "[Rn] 5f⁶ 7s²",
            melting_pt: 912.5, boiling_pt: 3505, state_at_stp: "solid",
            discovery_year: 1940, discoverer: "Glenn T. Seaborg",
            uses_zh: "核武器 (長崎原子彈)、太空船熱源 (RTG，如旅行者號)、核反應爐燃料。",
            uses_en: "Nuclear weapons (Nagasaki bomb), spacecraft heat sources (RTG, e.g. Voyager), reactor fuel.",
            fun_fact_zh: "新視野號和旅行者號探測器都靠鈽-238 衰變產生的熱在外太陽系運作。",
        }),
        E(95, "Am", "Americium", "鋂", 7, null, "actinide", {
            atomic_weight: 243, electron_config: "[Rn] 5f⁷ 7s²",
            melting_pt: 1449, boiling_pt: 2880, state_at_stp: "solid",
            discovery_year: 1944, discoverer: "Glenn T. Seaborg",
            uses_zh: "煙霧偵測器 (利用 α 粒子游離空氣)；幾乎是唯一在家中能找到的人工元素。",
            uses_en: "Smoke detectors (alpha particles ionize air); the only synthetic element commonly found in homes.",
            fun_fact_zh: "你家裡的煙霧偵測器幾乎都含有微量的鋂-241。",
        }),
        E(96, "Cm", "Curium", "鋦", 7, null, "actinide", {
            atomic_weight: 247, electron_config: "[Rn] 5f⁷ 6d¹ 7s²",
            melting_pt: 1613, boiling_pt: 3383, state_at_stp: "solid",
            discovery_year: 1944, discoverer: "Glenn T. Seaborg",
            uses_zh: "放射性熱源 (心律調節器、太空儀器)、X 光譜儀。",
            uses_en: "Radioactive heat sources (pacemakers, space instruments), X-ray spectrometers.",
            fun_fact_zh: "鋦以居禮夫婦命名，紀念他們對放射化學的貢獻。",
        }),
        E(97, "Bk", "Berkelium", "鉳", 7, null, "actinide", {
            atomic_weight: 247, electron_config: "[Rn] 5f⁹ 7s²",
            melting_pt: 1259, boiling_pt: 2900, state_at_stp: "solid",
            discovery_year: 1949, discoverer: "Glenn T. Seaborg",
            uses_zh: "純科學研究 (合成更重的元素)。",
            uses_en: "Pure research (synthesis of heavier elements).",
            fun_fact_zh: "鉳以發現地加州大學柏克萊分校命名。",
        }),
        E(98, "Cf", "Californium", "鉲", 7, null, "actinide", {
            atomic_weight: 251, electron_config: "[Rn] 5f¹⁰ 7s²",
            melting_pt: 1173, boiling_pt: 1743, state_at_stp: "solid",
            discovery_year: 1950, discoverer: "Glenn T. Seaborg",
            uses_zh: "中子源 (探油、礦物分析、癌症治療)；極少量產製。",
            uses_en: "Neutron sources (oil exploration, mineral analysis, cancer therapy); produced in tiny amounts.",
            fun_fact_zh: "1 微克鉲-252 每秒釋放 230 萬個中子，是極強的中子源。",
        }),
        E(99, "Es", "Einsteinium", "鎄", 7, null, "actinide", {
            atomic_weight: 252, electron_config: "[Rn] 5f¹¹ 7s²",
            melting_pt: 1133, boiling_pt: null, state_at_stp: "solid",
            discovery_year: 1952, discoverer: "Albert Ghiorso",
            uses_zh: "純科學研究；以愛因斯坦命名；發現於第一顆氫彈試爆殘骸中。",
            uses_en: "Pure research; named after Einstein; first found in H-bomb test debris.",
            fun_fact_zh: "鎄是在 1952 年「常春藤行動」氫彈試爆後在珊瑚礁殘骸中發現的。",
        }),
        E(100, "Fm", "Fermium", "鐨", 7, null, "actinide", {
            atomic_weight: 257, electron_config: "[Rn] 5f¹² 7s²",
            melting_pt: 1800, boiling_pt: null, state_at_stp: "solid",
            discovery_year: 1952, discoverer: "Albert Ghiorso",
            uses_zh: "純科學研究；以核物理之父費米 (Fermi) 命名。",
            uses_en: "Pure research; named after nuclear physics pioneer Enrico Fermi.",
            fun_fact_zh: "鐨是最後一個可以由中子捕獲產生的元素，再重的就只能用粒子加速器合成。",
        }),
        E(101, "Md", "Mendelevium", "鍆", 7, null, "actinide", {
            atomic_weight: 258, electron_config: "[Rn] 5f¹³ 7s²",
            melting_pt: 1100, boiling_pt: null, state_at_stp: "solid",
            discovery_year: 1955, discoverer: "Albert Ghiorso",
            uses_zh: "純科學研究；以週期表發明者門得列夫命名。",
            uses_en: "Pure research; named after Mendeleev, inventor of the periodic table.",
            fun_fact_zh: "鍆紀念週期表創建者門得列夫的開創性貢獻。",
        }),
        E(102, "No", "Nobelium", "鍩", 7, null, "actinide", {
            atomic_weight: 259, electron_config: "[Rn] 5f¹⁴ 7s²",
            melting_pt: 1100, boiling_pt: null, state_at_stp: "solid",
            discovery_year: 1966, discoverer: "Soviet/Joint Institute for Nuclear Research",
            uses_zh: "純科學研究；以炸藥發明人諾貝爾命名。",
            uses_en: "Pure research; named after Alfred Nobel, inventor of dynamite.",
            fun_fact_zh: "鍩是少數以諾貝爾命名的東西之一 (另一個就是諾貝爾獎)。",
        }),
        E(103, "Lr", "Lawrencium", "鐒", 7, null, "actinide", {
            atomic_weight: 266, electron_config: "[Rn] 5f¹⁴ 7s² 7p¹",
            melting_pt: 1900, boiling_pt: null, state_at_stp: "solid",
            discovery_year: 1961, discoverer: "Albert Ghiorso",
            uses_zh: "純科學研究；最後一個錒系元素；以迴旋加速器發明人勞倫斯命名。",
            uses_en: "Pure research; last actinide; named after cyclotron inventor Ernest Lawrence.",
            fun_fact_zh: "鐒結束了錒系元素，下一個鑪 (104) 就進入超鐒系元素。",
        }),
        // Transactinides 104-118 (compact)
        E(104, "Rf", "Rutherfordium", "鑪", 7, 4, "transition_metal", {
            atomic_weight: 267, electron_config: "[Rn] 5f¹⁴ 6d² 7s²",
            discovery_year: 1964, discoverer: "Joint Institute for Nuclear Research",
            uses_zh: "純科學研究；以原子核發現者拉塞福命名；半衰期僅秒級。",
            uses_en: "Pure research; named after atomic nucleus discoverer Ernest Rutherford; half-life in seconds.",
            fun_fact_zh: "鑪的命名曾引發美蘇冷戰時期的「超鐒戰爭」命名爭議。",
        }),
        E(105, "Db", "Dubnium", "𨧀", 7, 5, "transition_metal", {
            atomic_weight: 268, electron_config: "[Rn] 5f¹⁴ 6d³ 7s²",
            discovery_year: 1968, discoverer: "Joint Institute for Nuclear Research",
            uses_zh: "純科學研究；以俄羅斯核研究中心 Dubna 命名。",
            uses_en: "Pure research; named after the Russian nuclear research city Dubna.",
            fun_fact_zh: "𨧀的命名是冷戰結束後美蘇雙方達成的「外交妥協」結果之一。",
        }),
        E(106, "Sg", "Seaborgium", "𨭎", 7, 6, "transition_metal", {
            atomic_weight: 269, electron_config: "[Rn] 5f¹⁴ 6d⁴ 7s²",
            discovery_year: 1974, discoverer: "Lawrence Berkeley National Laboratory",
            uses_zh: "純科學研究；以發現多個錒系元素的西博格命名 (生前命名)。",
            uses_en: "Pure research; named after Glenn Seaborg (named while he was still alive).",
            fun_fact_zh: "西博格是極少數在生前就有元素以自己名字命名的科學家。",
        }),
        E(107, "Bh", "Bohrium", "𨨏", 7, 7, "transition_metal", {
            atomic_weight: 270, electron_config: "[Rn] 5f¹⁴ 6d⁵ 7s²",
            discovery_year: 1981, discoverer: "Gesellschaft für Schwerionenforschung",
            uses_zh: "純科學研究；以量子力學先驅波耳命名。",
            uses_en: "Pure research; named after quantum physics pioneer Niels Bohr.",
            fun_fact_zh: "𨨏曾被暫稱為 nielsbohrium，後來縮短為 bohrium。",
        }),
        E(108, "Hs", "Hassium", "𨭆", 7, 8, "transition_metal", {
            atomic_weight: 269, electron_config: "[Rn] 5f¹⁴ 6d⁶ 7s²",
            discovery_year: 1984, discoverer: "Gesellschaft für Schwerionenforschung",
            uses_zh: "純科學研究；以德國黑森邦 (Hesse) 命名。",
            uses_en: "Pure research; named after the German state of Hesse.",
            fun_fact_zh: "𨭆的化學性質研究只能在原子被生成後幾秒內完成。",
        }),
        E(109, "Mt", "Meitnerium", "䥑", 7, 9, "transition_metal", {
            atomic_weight: 278, electron_config: "[Rn] 5f¹⁴ 6d⁷ 7s²",
            discovery_year: 1982, discoverer: "Gesellschaft für Schwerionenforschung",
            uses_zh: "純科學研究；以核分裂發現者之一邁特納命名。",
            uses_en: "Pure research; named after Lise Meitner, co-discoverer of nuclear fission.",
            fun_fact_zh: "邁特納因性別而被諾貝爾獎忽視，元素命名是對她貢獻的補償。",
        }),
        E(110, "Ds", "Darmstadtium", "鐽", 7, 10, "transition_metal", {
            atomic_weight: 281, electron_config: "[Rn] 5f¹⁴ 6d⁸ 7s²",
            discovery_year: 1994, discoverer: "Gesellschaft für Schwerionenforschung",
            uses_zh: "純科學研究；以德國達姆施塔特市命名 (重離子研究所所在地)。",
            uses_en: "Pure research; named after Darmstadt, Germany (home of GSI).",
            fun_fact_zh: "鐽的所有同位素半衰期都不超過 10 秒。",
        }),
        E(111, "Rg", "Roentgenium", "錀", 7, 11, "transition_metal", {
            atomic_weight: 282, electron_config: "[Rn] 5f¹⁴ 6d⁹ 7s²",
            discovery_year: 1994, discoverer: "Gesellschaft für Schwerionenforschung",
            uses_zh: "純科學研究；以 X 光發現者倫琴命名。",
            uses_en: "Pure research; named after X-ray discoverer Wilhelm Röntgen.",
            fun_fact_zh: "錀以世界第一個諾貝爾物理獎得主倫琴命名，紀念 X 光發現百年。",
        }),
        E(112, "Cn", "Copernicium", "鎶", 7, 12, "transition_metal", {
            atomic_weight: 285, electron_config: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
            discovery_year: 1996, discoverer: "Gesellschaft für Schwerionenforschung",
            uses_zh: "純科學研究；以波蘭天文學家哥白尼命名。",
            uses_en: "Pure research; named after Polish astronomer Nicolaus Copernicus.",
            fun_fact_zh: "鎶在常溫下可能是液態金屬，是繼汞之後第二個液態金屬元素。",
        }),
        E(113, "Nh", "Nihonium", "鉨", 7, 13, "post_transition", {
            atomic_weight: 286, electron_config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
            discovery_year: 2003, discoverer: "RIKEN",
            uses_zh: "純科學研究；以日本 (Nihon) 命名，第一個由亞洲團隊發現的元素。",
            uses_en: "Pure research; named after Japan (Nihon); first element discovered by an Asian team.",
            fun_fact_zh: "鉨是亞洲科學家首次發現並命名的元素，2016 年正式公布。",
        }),
        E(114, "Fl", "Flerovium", "鈇", 7, 14, "post_transition", {
            atomic_weight: 289, electron_config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
            discovery_year: 1998, discoverer: "Joint Institute for Nuclear Research",
            uses_zh: "純科學研究；以蘇聯核物理學家弗廖羅夫命名。",
            uses_en: "Pure research; named after Soviet nuclear physicist Georgy Flyorov.",
            fun_fact_zh: "理論預測鈇會表現出類似鉛的性質而非氣體，但實驗結果尚未確定。",
        }),
        E(115, "Mc", "Moscovium", "鏌", 7, 15, "post_transition", {
            atomic_weight: 290, electron_config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
            discovery_year: 2003, discoverer: "Joint Institute for Nuclear Research",
            uses_zh: "純科學研究；以俄羅斯莫斯科州命名。",
            uses_en: "Pure research; named after Moscow Oblast, Russia.",
            fun_fact_zh: "鏌的所有觀察到的同位素半衰期都不到 1 秒。",
        }),
        E(116, "Lv", "Livermorium", "鉝", 7, 16, "post_transition", {
            atomic_weight: 293, electron_config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
            discovery_year: 2000, discoverer: "Joint Institute for Nuclear Research",
            uses_zh: "純科學研究；以美國勞倫斯利弗莫爾國家實驗室命名。",
            uses_en: "Pure research; named after Lawrence Livermore National Laboratory.",
            fun_fact_zh: "鉝是合作研究的成果，由美俄科學家共同合成。",
        }),
        E(117, "Ts", "Tennessine", "鿬", 7, 17, "halogen", {
            atomic_weight: 294, electron_config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
            discovery_year: 2010, discoverer: "Joint Institute for Nuclear Research",
            uses_zh: "純科學研究；以美國田納西州命名 (橡樹嶺國家實驗室所在地)。",
            uses_en: "Pure research; named after Tennessee (Oak Ridge National Lab).",
            fun_fact_zh: "鿬是週期表第 17 族 (鹵素) 的最重成員，但化學行為可能更像金屬。",
        }),
        E(118, "Og", "Oganesson", "鿫", 7, 18, "noble_gas", {
            atomic_weight: 294, electron_config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
            discovery_year: 2002, discoverer: "Joint Institute for Nuclear Research",
            uses_zh: "純科學研究；目前週期表最後一個元素；以俄羅斯科學家奧加涅相命名。",
            uses_en: "Pure research; currently the last element on the periodic table; named after Yuri Oganessian.",
            fun_fact_zh: "鿫是目前已知最重的元素，也是少數以在世科學家命名的元素之一。",
        }),
    ];

    // Build map: tile value (2^no) → element entry
    const byTile = {};
    const byNo = {};
    for (const el of elements) {
        // Tile values for n > 53 exceed JS safe integer; use Math.pow which gives Number
        // (still useful as a key even if not a valid game tile)
        const tileVal = Math.pow(2, el.no);
        byTile[tileVal] = el;
        byNo[el.no] = el;
    }

    // Expose
    window.PERIODIC_ELEMENTS = elements;
    window.PERIODIC_BY_TILE = byTile;
    window.PERIODIC_BY_NO = byNo;
    window.PERIODIC_CAT_COLORS = CAT_COLORS;
})();
